In [1]:
api_key = 'LhEvgrgZLKCqij8TJUx_'
import Quandl
mydata = Quandl.get("FRED/GDP",  authtoken=api_key)

In [4]:
Quandl.get("NVCA/VENTURE_3_08", authtoken="LhEvgrgZLKCqij8TJUx_")

,AK/HI/PR,Colorado,DC/Metroplex,LA/Orange County,Midwest,New England,North Central,Northwest,NY Metro,Philadelphia Metro,Sacramento/N.Cal,San Diego,Silicon Valley,South Central,Southeast,SouthWest,Texas,Unknown,Upstate NY,Total
Date,,,,,,,,,,,,,,,,,,,,
1985-12-31,758.8000,435.4000,221.2000,196.5000,157.5000,99.6000,142.2000,249.0000,166.4000,99.1000,77.0000,40.1000,52.6000,37.0000,13.7000,14.2000,NaN,16.0000,NaN,2776.4000
1986-12-31,1016.3000,436.6000,211.0000,186.9000,139.9000,95.4000,142.9000,228.4000,234.2000,61.1000,113.8000,82.5000,63.3000,44.5000,11.4000,10.7000,NaN,45.5000,NaN,3124.5000
1987-12-31,849.9000,525.1000,273.9000,276.9000,198.4000,107.8000,153.3000,211.0000,271.0000,111.8000,111.4000,57.5000,79.2000,73.6000,19.8000,10.2000,0.5000,32.0000,NaN,3363.6000
1988-12-31,985.9000,496.9000,308.0000,222.5000,132.3000,149.8000,141.2000,240.7000,266.5000,129.9000,107.8000,59.7000,71.8000,41.6000,11.7000,5.3000,0.8000,33.6000,NaN,3406.0000
1989-12-31,916.5000,404.7000,360.4000,242.1000,183.2000,145.5000,118.0000,228.3000,224.4000,139.5000,157.8000,50.7000,65.3000,51.2000,14.5000,7.3000,6.1000,4.2000,NaN,3319.6000
1990-12-31,914.1000,425.0000,190.1000,174.7000,155.9000,113.3000,88.2000,141.0000,145.9000,96.9000,93.7000,30.3000,105.9000,92.2000,11.6000,11.1000,13.0000,19.5000,NaN,2822.4000
1991-12-31,780.5000,287.0000,181.5000,119.4000,181.4000,115.7000,59.9000,161.4000,109.4000,51.3000,54.2000,49.0000,34.7000,44.9000,4.2000,3.4000,0.2000,15.7000,0.3000,2254.0000
1992-12-31,1119.5000,417.0000,239.0000,179.4000,165.2000,111.2000,252.1000,149.6000,346.6000,65.8000,129.7000,98.4000,168.9000,89.1000,6.5000,9.1000,30.8000,8.5000,0.0000,3586.3000
1993-12-31,903.2000,358.4000,222.3000,176.4000,276.9000,133.0000,118.4000,240.7000,405.8000,384.1000,135.0000,49.7000,108.3000,109.6000,8.6000,5.7000,0.8000,19.1000,1.0000,3656.8000
1994-12-31,1074.4000,440.4000,283.3000,198.4000,432.6000,220.5000,165.7000,311.8000,362.3000,137.8000,197.4000,38.0000,137.6000,87.4000,15.2000,0.7000,0.1000,20.0000,22.0000,4157.6000
1995-12-31,7.7600,325.0535,415.1680,1004.0980,470.4157,796.5875,223.7910,379.7190,509.7186,220.8566,19.9849,276.7867,1807.8357,45.2221,885.3897,113.0560,479.2284,0.3200,35.5320,8016.5234
1996-12-31,28.7030,321.2238,585.4604,614.0571,736.1767,1164.1351,224.7025,555.9807,761.9862,365.6878,28.6140,485.2099,3365.9802,71.6251,1178.0900,184.5652,588.3774,2.1728,22.6751,11285.4230
1997-12-31,13.9960,405.0407,500.8025,861.1247,913.4786,1620.5153,341.6140,564.3647,1295.0842,534.2201,21.3749,515.9846,4627.3392,67.4249,1436.6686,303.0644,954.7795,4.3798,90.2979,15071.5546
1998-12-31,5.4650,841.9264,1148.7186,1223.0822,1646.5346,2375.0120,437.3486,820.3220,1849.1183,666.4505,86.7930,662.8694,5865.7939,196.7030,1828.0264,413.4148,1244.4744,54.0570,195.4213,21561.5314
1999-12-31,17.3550,1832.9392,2395.1369,3593.7029,2631.1107,5677.1443,769.9582,2874.5666,4647.3210,1732.5623,119.1134,1426.9565,17768.3948,360.0589,4830.9794,843.1151,3173.3410,2.4010,212.4402,54908.5974
2000-12-31,248.6150,4096.0554,5795.2238,6773.6884,5725.7097,12115.6590,1397.3056,3606.3909,10188.5697,2487.5156,372.2815,2317.6411,33417.0331,446.9408,7971.0670,1438.0125,6255.7712,50.4230,293.9445,104997.8478
2001-12-31,69.8110,1245.4955,2103.0551,2247.6841,2184.5316,5404.2117,669.5603,1342.2132,3497.5642,1086.6071,203.0189,1591.2243,12668.6796,110.4143,2685.6834,515.1487,3140.2902,14.3090,159.0990,40938.6012
2002-12-31,4.8950,598.6513,1096.5876,1278.7661,976.9477,3016.0408,433.7042,770.3777,1543.3402,607.8367,65.3600,1002.3952,7259.8905,69.3361,1778.8498,393.8374,1195.6414,NaN,110.0950,22202.5527
2003-12-31,17.9290,613.8897,791.9454,1069.1609,913.9134,3103.4669,268.7262,659.9567,1386.5956,530.5893,32.1768,831.9475,6728.7340,49.9420,1111.0391,218.0620,1222.9554,NaN,131.1307,19682.1606
2004-12-31,15.1400,363.1904,1086.6005,921.4676,701.3615,3417.2589,464.4816,1014.2193,1634.5576,763.9978,38.4439,1207.8807,7983.0123,130.1232,1403.7312,386.8105,1215.1060,NaN,104.8080,22852.1910
2005-12-31,43.3138,617.5498,1238.7688,1498.1690,919.3401,2981.3991,367.3058,1016.7496,1640.6598,593.9201,37.7310,1225.7336,8145.6808,96.0911,1077.5412,507.0252,1178.3279,NaN,60.0610,23245.3677
2006-12-31,47.0671,705.1962,1355.2755,1909.8670,998.7576,3436.0573,391.6953,1307.4771,2325.0299,837.6568,31.4761,1247.0778,9754.7856,57.3161,1261.3079,520.5530,1523.6981,NaN,156.1255,27866.4199
2007-12-31,20.9490,686.2893,1409.5228,1952.5284,1202.0711,4145.2189,528.3085,1638.1334,1927.5797,891.8927,76.6768,1873.8848,11531.6311,106.2852,1859.2313,609.8869,1509.5028,0.0000,136.5320,32106.1247
2008-12-31,21.3000,891.6389,1168.3329,2115.1816,1346.1789,3851.1518,626.1336,1073.5689,2207.6024,798.9238,69.2989,1184.5716,11546.3952,91.2911,1315.8866,572.8402,1463.0469,NaN,92.2550,30435.5983
2009-12-31,7.3640,463.1882,684.6836,1052.3627,956.6073,2584.1484,427.6506,659.9993,1776.7474,409.5823,18.8140,954.8455,8283.4580,16.7932,1034.3715,298.1558,679.7224,0.5250,26.8880,20335.9072
2010-12-31,9.2445,464.3626,1001.7086,1673.8336,1405.7695,2613.7148,320.7197,756.7873,1897.9238,499.1991,26.9361,847.9308,9394.6084,66.8761,1092.2088,286.7460,1121.5783,0.0000,44.7690,23524.9170
2011-12-31,0.6000,660.8914,1019.6791,2049.1118,1521.4417,3313.7769,365.9860,716.5730,2903.4768,454.3168,87.8309,927.9586,12246.5003,60.7911,1240.2814,590.9717,1630.6139,0.0000,112.7148,29903.5162
2012-12-31,0.7450,627.5073,753.2741,2141.6452,1429.4591,3557.4310,348.3359,1010.1048,2333.2651,414.6882,20.0191,1183.3346,11231.2552,92.8239,847.8938,597.9853,1025.5380,0.2000,47.4381,27662.9437
2013-12-31,0.7030,472.5011,1575.7397,1845.7072,1064.9392,3291.2353,380.2762,1048.9624,3214.2762,429.8312,41.7310,721.7301,12771.9096,132.3182,1377.2022,476.0802,1324.7470,NaN,116.0433,30285.9331
2014-12-31,0.3500,817.4247,1092.0715,2957.7043,2159.1117,4981.0006,505.7355,1535.2283,5276.2440,488.1716,128.8091,833.7753,25428.5013,132.3413,1916.5536,1113.8475,1426.8112,2.6000,39.3720,50835.6535
2015-12-31,NaN,782.6226,1414.5681,5105.6551,2248.8736,6052.8153,598.8985,1501.7909,7317.2475,609.8984,43.2158,1166.5687,27347.8317,106.4328,2258.9383,919.0467,1170.7884,6.3200,159.6759,58811.1883